/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html", "./src/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1a1c19",
        error: "#ffb4ab",
        "primary-container": "#1a1c19",
        "secondary-container": "#4a4c48",
        "outline-variant": "#454843",
        "primary-fixed-dim": "#c6c7c2",
        surface: "#111213",
        "on-surface-variant": "#c5c7c1",
        "tertiary-fixed-dim": "#4de082",
        "on-primary-container": "#838480",
        "on-surface": "#e2e3dd",
        background: "#111213",
        "surface-container-highest": "#333532",
        "surface-tint": "#c6c7c2",
        "on-secondary-container": "#bbbcb8",
        "on-tertiary-container": "#00984d",
        primary: "#c6c7c2",
        "on-secondary": "#2f312e",
        "surface-container-high": "#282b27",
        "surface-container-low": "#1a1c19",
        "on-primary-fixed-variant": "#464744",
        "tertiary-container": "#00210c",
        "surface-container-lowest": "#0c0e0d",
        "tertiary-fixed": "#6dfe9c",
        "on-error-container": "#ffdad6",
        "on-background": "#e2e3dd",
        "surface-bright": "#373a36",
        tertiary: "#4de082",
        "on-tertiary": "#003919",
        "secondary-fixed-dim": "#c6c7c2",
        "primary-fixed": "#e3e3de",
        "on-primary": "#2f312e",
        "inverse-surface": "#e2e3dd",
        "surface-container": "#1e201d",
        "inverse-primary": "#5d5f5b",
        outline: "#8f918c",
        secondary: "#c6c7c2",
        "on-secondary-fixed-variant": "#454744",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#005227",
        "error-container": "#93000a",
        "on-primary-fixed": "#1a1c19",
        "on-tertiary-fixed": "#00210c",
        "secondary-fixed": "#e2e3de",
        "inverse-on-surface": "#2e312d",
        "surface-dim": "#111411",
        "surface-variant": "#333532",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        unit: "8px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        gutter: "24px",
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "label-caps": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "label-sm": ["13px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
